name: Sync GitHub Issues to MantisHub

on:
  issues:
    types: [opened]

jobs:
  create-mantis-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Call MantisHub API to create issue
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.issue.title;
            const description = context.payload.issue.body || "Sem descrição.";

            const res = await fetch(process.env.MANTISHUB_API_URL + "/api/rest/issues/", {
              method: "POST",
              headers: {
                "Authorization": process.env.MANTISHUB_API_TOKEN,
                "Content-Type": "application/json"
              },
              body: JSON.stringify({
                summary: title,
                description: description,
                category: "General",  
                project: {
                  id: parseInt(process.env.MANTISHUB_PROJECT_ID)
                }
              })
            });

            if (!res.ok) {
              const error = await res.text();
              core.setFailed(`Erro ao criar issue no MantisHub: ${error}`);
            } else {
              console.log("Issue criada com sucesso no MantisHub!");
            }
        env:
          MANTISHUB_API_URL: ${{ secrets.MANTISHUB_API_URL }}
          MANTISHUB_API_TOKEN: ${{ secrets.MANTISHUB_API_TOKEN }}
          MANTISHUB_PROJECT_ID: ${{ secrets.MANTISHUB_PROJECT_ID }}
