name: SonarQube + Criar Issues

on:
  push:
    branches:
      - master

jobs:
  sonarqube-analysis:
    runs-on: self-hosted

    steps:
      - name: Clonar código
        uses: actions/checkout@v3

      - name: Análise SonarQube
        shell: cmd
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner ^
            C:\Users\moise\Downloads\sonar-scanner-7.1.0.4889-windows-x64\bin\sonar-scanner.bat
            -Dsonar.projectKey=projetoSonar-mantis ^
            -Dsonar.host.url=http://localhost:9000 ^
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          

      - name: Criar issues via PHP
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_PAT: ${{ secrets.GH_PAT }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: C:\php\php.exe scripts/create_issues.php
