name: SonarQube + Criar Issues

on:
  push:
    branches:
      - main

jobs:
  sonarqube-analysis:
    runs-on: self-hosted

    steps:
      - name: Clonar código
        uses: actions/checkout@v3

      - name: Análise SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner ^
            -Dsonar.projectKey=MES987654321 ^
            -Dsonar.host.url=http://localhost:9000 ^
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Criar issues via PHP
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: php scripts/create_issues.php
